"""Ajout de status2

Revision ID: 05690039a3c2
Revises: 18e3346c903d
Create Date: 2025-04-02 10:55:28.193931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05690039a3c2'
down_revision = '18e3346c903d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_request_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint('fk_request_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
