"""Ajout de status

Revision ID: 18e3346c903d
Revises: 
Create Date: 2025-04-01 20:44:34.705912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e3346c903d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('object_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_request_object', 'object', ['object_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('object_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
