"""Recréation des migrations

Revision ID: 5ff94c9faf13
Revises: 
Create Date: 2025-03-20 19:29:28.672402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff94c9faf13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pseudo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('firstname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_pseudo'), ['pseudo'], unique=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=1000), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_pseudo'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_column('gender')
        batch_op.drop_column('age')
        batch_op.drop_column('firstname')
        batch_op.drop_column('lastname')
        batch_op.drop_column('pseudo')

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pseudo', sa.VARCHAR(length=100), nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('gender', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
