"""MajBDD3

Revision ID: 74901fb0d592
Revises: 142f62fb3dfe
Create Date: 2025-04-06 15:49:54.260966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74901fb0d592'
down_revision = '142f62fb3dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###
