"""MajBDD

Revision ID: 8e9766187ac2
Revises: 05690039a3c2
Create Date: 2025-04-02 12:44:37.476666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9766187ac2'
down_revision = '05690039a3c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info')
    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_object_nom'), ['nom'], unique=True)

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('object_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('user_lastname', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('user_firstname', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=True))
        batch_op.drop_constraint('fk_request_user', type_='foreignkey')
        batch_op.drop_constraint('fk_request_object', type_='foreignkey')
        batch_op.drop_column('object_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('point', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('point')
        batch_op.drop_column('role')

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('object_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_request_object', 'object', ['object_id'], ['id'])
        batch_op.create_foreign_key('fk_request_user', 'user', ['user_id'], ['id'])
        batch_op.drop_column('image')
        batch_op.drop_column('user_firstname')
        batch_op.drop_column('user_lastname')
        batch_op.drop_column('object_type')
        batch_op.drop_column('object_name')

    with op.batch_alter_table('object', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_object_nom'))

    op.create_table('info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
